### PR TITLE
fix can’t feedback bug;update some code;

### PR DESCRIPTION
**Pull request by obetame**
this pull request just test😝.
i see dev branches use *riot.js*~  it seems like a test

### CODE REVIEW

**Comment by poppinlp** [comment]
I have opend some issues which should be done in new version.
You could see which one you are interested in.

**Comment by poppinlp** [comment]
Yep it's a test on dev br.
@zhouyuexie  We could make a discuss about which framework to use.
I'm free to react-like or vue-like.

**Comment by obetame** [comment]
Fine,i would start at once if I had time.
i like vue template,maybe...

**Comment by poppinlp** [comment]
Not ASAP case here compared to our JIRA case.

**Comment by obetame** [comment]
[this JIRA case](http://jira.ricequant.com/browse/ENG-4233) waiting for [new man](http://jira.ricequant.com/secure/ViewProfile.jspa?name=newman) data.

**Pull request merged**
